services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./site/:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  grafana:
    image: grafana/grafana-enterprise:${GRAFANA_VERSION}
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_COOKIE_SAMESITE=lax
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/GF_SECURITY_ADMIN_USER__FILE
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/GF_SECURITY_ADMIN_PASSWORD__FILE
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
    secrets:
      - GF_SECURITY_ADMIN_USER__FILE
      - GF_SECURITY_ADMIN_PASSWORD__FILE
    depends_on:
      - influxdb2
      
  influxdb2:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: ${INFLUXDB_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - '${INFLUXDB_PORT}:8086'
    env_file:
      - ./.env
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
  telegraf:
    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: telegraf
    restart: always
    env_file:
      - ./.env
    secrets:
      - influxdb2-admin-token
    volumes:
      - ${TELEGRAF_CONF_FILE}:/etc/telegraf/telegraf.conf:ro
      - ./py/script.py:/scripts/script.py:ro
    depends_on:
      - influxdb2

volumes:
  grafana_storage: {}
  influxdb2-data: {}
  influxdb2-config: {}

secrets:
  influxdb2-admin-username:
    file: ./secrets/influxdb2-admin-username
  influxdb2-admin-password:
    file: ./secrets/influxdb2-admin-password
  influxdb2-admin-token:
    file: ./secrets/influxdb2-admin-token
  GF_SECURITY_ADMIN_USER__FILE:
    file: ./secrets/grafana-admin-username
  GF_SECURITY_ADMIN_PASSWORD__FILE:
    file: ./secrets/grafana-admin-password
